version: '3'
services: 
  web:
    container_name: apache
    ports: 
      - "8080:80"
    image: httpd
    networks: 
      - net-test
  web2:
    container_name: apache2
    ports: 
      - "8081:80"
    image: httpd
    networks: 
      - net-test
      - net-demo
networks: 
  net-test:
  net-demo: